baseURL = "https://goshsamit.com"
defaultContentLanguage = "en"
# Automatically generate robots.txt
enableRobotsTXT = true
languageCode = "en"
theme = "gokarna"
title = "goshSAMit"

[params]
  # avatarAltText = "avatar"
  # avatarSize = "size-m"
  # avatarURL = "/images/avatar.webp"

  description = "Sam | Columbus | Senior Quality Engineer"
  showPostsOnHomePage = ""
  numberPostsOnHomePage = 4
  togglePreviousAndNextButtons = false
  dateFormat = "2 January, 2006"

[menu]
  [[menu.main]]
    name = "About Me" # Display name
    url = "/about-me/" # Relative URL slug (appended to baseURL)
    weight = 1 # Lower weights are listed first in the menu (leftmost); higher weights are listed last in the menu (rightmost)
    pre = "<span data-feather='user'></span>" #Feather icons: https://feathericons.com

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
    pre = "<span data-feather='terminal'></span>"

  [[menu.main]]
    name = "Topics"
    url = "/Topics/"
    weight = 3
    pre = "<span data-feather='list'></span>"

  [[menu.main]]
    identifier = "tags"
    url = "/tags/"
    weight = 4
    pre = "<span data-feather='tag'></span>"
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/goshsamit"
    weight = 5
    pre = "<span data-feather='github'></span>"
    post = ""

    [[menu.main]]
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/goshsamit/"
    weight = 6
    pre = "<span data-feather='linkedin'></span>"
    post = ""
