baseURL = "https://goshsamit.com"
defaultContentLanguage = "en"
# Automatically generate robots.txt
enableRobotsTXT = true
languageCode = "en"
theme = "gokarna"
title = "goshSAMit"

[params]
  # avatarAltText = "avatar"
  # avatarSize = "size-m"
  # avatarURL = "/images/avatar.webp"

  description = "description"
  showPostsOnHomePage = "recent"
  numberPostsOnHomePage = 4
  togglePreviousAndNextButtons = false

[menu]
  [[menu.main]]
    name = "About Me"
    url = "/about-me/"
    weight = 1
    pre = "<span data-feather='user'></span>"

  [[menu.main]]
    # Display name
    name = "Posts"
    # Relative URL slug (appended to baseURL)
    url = "/posts/"
    # Lower weights are listed first in the menu (leftmost); higher weights are
    # listed last in the menu (rightmost)
    weight = 2
    pre = "<span data-feather='list'></span>"

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
    pre = "<span data-feather='tag'></span>"
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/goshsamit"
    weight = 4
    # Surround the menu entry (or name) with HTML content, such as Feather
    # icons: https://feathericons.com
    pre = "<span data-feather='github'></span>"
    post = ""

    [[menu.main]]
    identifier = "linkedin"
    url = "https://github.com/goshsamit"
    weight = 5
    pre = "<span data-feather='linkedin'></span>"
    post = ""
